### ISSUE TITLE
JPEG files do not save in the correct orientation

### ISSUE THREAD

**Issue by reilandeubank** [reilandeubank/unprocess#4]
Currently, after taking an image to be saved as JPEG, the image viewer displays it correctly oriented, but upon saving, the image is always landscape.

**Comment by Ytrog** [comment]
Do you save with EXIF-data included? You might look into that, especially the `orientation` tag. See: https://exiftool.org/TagNames/EXIF.html 🤔

**Comment by reilandeubank** [comment]
@Ytrog Thank you for the suggestion! I just added #9 to address this.

**Comment by Ytrog** [comment]
> @Ytrog Thank you for the suggestion! I just added #9 to address this.

Glad I could help ☺
